// config.js
const PAIRS_CONFIG = {
  menu: [
    { id: "btn1", title: "Currencies", sub: "Forex pairs" },
    { id: "btn2", title: "Stocks", sub: "Company shares" },
    { id: "btn3", title: "Crypto", sub: "Digital assets" },
    { id: "btn4", title: "Commodities", sub: "More options" }
  ],
  popularPairs: [
    { flag1: "us", flag2: "eu", label: "USD/EUR" },
    { flag1: "gb", flag2: "us", label: "GBP/USD" },
    { flag1: "jp", flag2: "us", label: "USD/JPY" },
    { flag1: "ca", flag2: "us", label: "CAD/USD" },
    { flag1: "btc", flag2: "us", label: "BTC/USD" },
    { flag1: "ch", flag2: "us", label: "CHF/USD" }
  ],
  otcPairs: [
    { flag1: "xx", flag2: "xx", label: "OTC Pair 1" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 2" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 3" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 4" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 5" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 6" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 7" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 8" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 9" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 10" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 11" },
    { flag1: "xx", flag2: "xx", label: "OTC Pair 12" }
  ],
  stockPairs: [
    { flag1: "xx", flag2: "xx", label: "STOCK Pair 1" },
    { flag1: "xx", flag2: "xx", label: "STOCK Pair 2" },
    { flag1: "xx", flag2: "xx", label: "STOCK Pair 3" },
    { flag1: "xx", flag2: "xx", label: "STOCK Pair 4" }
  ],
  cryptoPairs: [
    // OTC Crypto Pairs (12 pairs)
    { label: "DOGE" },
    { label: "SOL" },
    { label: "TON" },
    { label: "TRX" },
    { label: "LINK" },
    { label: "BTC" },
    { label: "ETH" },
    { label: "AVAX" },
    { label: "BTCETF" },
    { label: "DOT" },
    { label: "MATIC" },
    { label: "BNB" },
    // Stock Crypto Pairs (4 pairs)
    { label: "LINK" },
    { label: "ETH" },
    { label: "BTC" },
    { label: "DASH" }
  ],
  commoditiesPairs: [
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 1" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 2" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 3" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 4" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 5" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 6" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 7" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 8" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 9" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 10" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 11" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 12" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 13" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 14" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 15" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 16" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 17" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 18" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 19" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 20" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 21" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 22" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 23" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 24" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 25" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 26" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 27" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 28" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 29" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 30" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 31" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 32" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 33" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 34" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 35" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 36" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 37" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 38" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 39" },
    { flag1: "xx", flag2: "xx", label: "COMMODITY Pair 40" }
  ],
  forexPairs: [
    { flag1: "au", flag2: "ch", label: "AUD/CHF" },
    { flag1: "ca", flag2: "jp", label: "CAD/JPY" },
    { flag1: "eu", flag2: "ch", label: "EUR/CHF" },
    { flag1: "eu", flag2: "gb", label: "EUR/GBP" },
    { flag1: "eu", flag2: "jp", label: "EUR/JPY" },
    { flag1: "eu", flag2: "ru", label: "EUR/RUB" },
    { flag1: "eu", flag2: "us", label: "EUR/USD" },
    { flag1: "jo", flag2: "cn", label: "JOD/CNY" },
    { flag1: "lb", flag2: "us", label: "LBP/USD" },
    { flag1: "ng", flag2: "us", label: "NGN/USD" },
    { flag1: "nz", flag2: "us", label: "NZD/USD" },
    { flag1: "om", flag2: "cn", label: "OMR/CNY" },
    { flag1: "tn", flag2: "us", label: "TND/USD" },
    { flag1: "us", flag2: "bd", label: "USD/BDT" },
    { flag1: "us", flag2: "ch", label: "USD/CHF" },
    { flag1: "us", flag2: "dz", label: "USD/DZD" },
    { flag1: "us", flag2: "mx", label: "USD/MXN" },
    { flag1: "us", flag2: "ph", label: "USD/PHP" },
    { flag1: "ye", flag2: "us", label: "YER/USD" },
    { flag1: "us", flag2: "co", label: "USD/COP" },
    { flag1: "us", flag2: "vn", label: "USD/VND" },
    { flag1: "us", flag2: "ru", label: "USD/RUB" },
    { flag1: "ch", flag2: "no", label: "CHF/NOK" },
    { flag1: "au", flag2: "ca", label: "AUD/CAD" },
    { flag1: "bh", flag2: "cn", label: "BHD/CNY" },
    { flag1: "gb", flag2: "au", label: "GBP/AUD" },
    { flag1: "us", flag2: "ar", label: "USD/ARS" },
    { flag1: "gb", flag2: "jp", label: "GBP/JPY" },
    { flag1: "au", flag2: "jp", label: "AUD/JPY" },
    { flag1: "us", flag2: "my", label: "USD/MYR" },
    { flag1: "eu", flag2: "nz", label: "EUR/NZD" },
    { flag1: "za", flag2: "us", label: "ZAR/USD" },
    { flag1: "us", flag2: "ca", label: "USD/CAD" },
    { flag1: "us", flag2: "eg", label: "USD/EGP" },
    { flag1: "ua", flag2: "us", label: "UAH/USD" },
    { flag1: "ca", flag2: "ch", label: "CAD/CHF" },
    { flag1: "ch", flag2: "jp", label: "CHF/JPY" },
    { flag1: "eu", flag2: "tr", label: "EUR/TRY" },
    { flag1: "ma", flag2: "us", label: "MAD/USD" },
    { flag1: "us", flag2: "cn", label: "USD/CNH" }
  ],
  times: [
    { time: "5s", emoji: "⚡", sub: "Ultra" },
    { time: "15s", emoji: "🔥", sub: "Fast" },
    { time: "30s", emoji: "🎯", sub: "Stable" },
    { time: "1m", emoji: "⭐", sub: "Beginner" },
    { time: "3m", emoji: "📊", sub: "Analysis" },
    { time: "5m", emoji: "⏳", sub: "Long" }
  ],
  loadingSteps: ["Connecting to TradingView...", "Fetching indicators...", "Analyzing..."],
  buyIndicators: ["RSI", "MACD", "Volume", "MA Cross", "Bollinger Bands", "Breakout", "Support"],
  sellIndicators: ["RSI", "MACD", "Volume", "MA Cross", "Bollinger Bands", "Resistance", "Breakdown"]
};