const PAIRS_CONFIG = {
  menu: [
    { id: "btn1", title: "Pair Selection", sub: "Forex pairs" }
  ],
  popularPairs: [
    { flag1: "us", flag2: "eu", label: "USD/EUR" },
    { flag1: "gb", flag2: "us", label: "GBP/USD" },
    { flag1: "jp", flag2: "us", label: "USD/JPY" },
    { flag1: "ca", flag2: "us", label: "CAD/USD" },
    { flag1: "au", flag2: "us", label: "AUD/USD" },
    { flag1: "eu", flag2: "ch", label: "EUR/CHF" }
  ],
  categories: {
    currencies: {
      otc: [
        { flag1: "au", flag2: "ca", label: "AUD/CAD" },
        { flag1: "au", flag2: "us", label: "AUD/USD" },
        { flag1: "eu", flag2: "ch", label: "EUR/CHF" },
        { flag1: "eu", flag2: "nz", label: "EUR/NZD" },
        { flag1: "eu", flag2: "tr", label: "EUR/TRY" },
        { flag1: "eu", flag2: "us", label: "EUR/USD" },
        { flag1: "ng", flag2: "us", label: "NGN/USD" },
        { flag1: "nz", flag2: "us", label: "NZD/USD" },
        { flag1: "us", flag2: "bd", label: "USD/BDT" },
        { flag1: "us", flag2: "ca", label: "USD/CAD" },
        { flag1: "us", flag2: "cl", label: "USD/CLP" },
        { flag1: "us", flag2: "id", label: "USD/IDR" },
        { flag1: "us", flag2: "mx", label: "USD/MXN" },
        { flag1: "ye", flag2: "us", label: "YER/USD" },
        { flag1: "au", flag2: "nz", label: "AUD/NZD" },
        { flag1: "ch", flag2: "no", label: "CHF/NOK" },
        { flag1: "bh", flag2: "cn", label: "BHD/CNY" },
        { flag1: "eu", flag2: "gb", label: "EUR/GBP" },
        { flag1: "us", flag2: "ph", label: "USD/PHP" },
        { flag1: "us", flag2: "sg", label: "USD/SGD" },
        { flag1: "us", flag2: "vn", label: "USD/VND" },
        { flag1: "gb", flag2: "jp", label: "GBP/JPY" },
        { flag1: "gb", flag2: "us", label: "GBP/USD" },
        { flag1: "ua", flag2: "us", label: "UAH/USD" },
        { flag1: "eu", flag2: "hu", label: "EUR/HUF" },
        { flag1: "au", flag2: "jp", label: "AUD/JPY" },
        { flag1: "us", flag2: "dz", label: "USD/DZD" },
        { flag1: "us", flag2: "jp", label: "USD/JPY" },
        { flag1: "us", flag2: "my", label: "USD/MYR" },
        { flag1: "tn", flag2: "us", label: "TND/USD" },
        { flag1: "us", flag2: "br", label: "USD/BRL" },
        { flag1: "us", flag2: "th", label: "USD/THB" },
        { flag1: "ke", flag2: "us", label: "KES/USD" },
        { flag1: "ch", flag2: "jp", label: "CHF/JPY" },
        { flag1: "qa", flag2: "cn", label: "QAR/CNY" },
        { flag1: "us", flag2: "ar", label: "USD/ARS" },
        { flag1: "us", flag2: "eg", label: "USD/EGP" },
        { flag1: "us", flag2: "in", label: "USD/INR" },
        { flag1: "jo", flag2: "cn", label: "JOD/CNY" },
        { flag1: "sa", flag2: "cn", label: "SAR/CNY" },
        { flag1: "nz", flag2: "jp", label: "NZD/JPY" },
        { flag1: "us", flag2: "pk", label: "USD/PKR" },
        { flag1: "us", flag2: "cn", label: "USD/CNH" },
        { flag1: "au", flag2: "ch", label: "AUD/CHF" },
        { flag1: "om", flag2: "cn", label: "OMR/CNY" },
        { flag1: "lb", flag2: "us", label: "LBP/USD" },
        { flag1: "ma", flag2: "us", label: "MAD/USD" },
        { flag1: "eu", flag2: "jp", label: "EUR/JPY" },
        { flag1: "gb", flag2: "au", label: "GBP/AUD" },
        { flag1: "us", flag2: "co", label: "USD/COP" },
        { flag1: "us", flag2: "ch", label: "USD/CHF" },
        { flag1: "us", flag2: "ru", label: "USD/RUB" },
        { flag1: "za", flag2: "us", label: "ZAR/USD" },
        { flag1: "eu", flag2: "ru", label: "EUR/RUB" },
        { flag1: "ca", flag2: "ru", label: "CAD/RUB" },
        { flag1: "ca", flag2: "ch", label: "CAD/CHF" },
        { flag1: "ae", flag2: "cn", label: "AED/CNY" }
      ],
      stock: [
        { flag1: "ca", flag2: "ch", label: "CAD/CHF" },
        { flag1: "gb", flag2: "ca", label: "GBP/CAD" },
        { flag1: "ch", flag2: "jp", label: "CHF/JPY" },
        { flag1: "eu", flag2: "au", label: "EUR/AUD" },
        { flag1: "au", flag2: "jp", label: "AUD/JPY" },
        { flag1: "ca", flag2: "jp", label: "CAD/JPY" },
        { flag1: "au", flag2: "ch", label: "AUD/CHF" },
        { flag1: "eu", flag2: "us", label: "EUR/USD" },
        { flag1: "eu", flag2: "jp", label: "EUR/JPY" },
        { flag1: "gb", flag2: "us", label: "GBP/USD" },
        { flag1: "gb", flag2: "ch", label: "GBP/CHF" },
        { flag1: "us", flag2: "ch", label: "USD/CHF" },
        { flag1: "eu", flag2: "gb", label: "EUR/GBP" },
        { flag1: "eu", flag2: "ca", label: "EUR/CAD" },
        { flag1: "eu", flag2: "ch", label: "EUR/CHF" },
        { flag1: "au", flag2: "us", label: "AUD/USD" },
        { flag1: "us", flag2: "ca", label: "USD/CAD" },
        { flag1: "au", flag2: "ca", label: "AUD/CAD" },
        { flag1: "us", flag2: "jp", label: "USD/JPY" },
        { flag1: "gb", flag2: "ch", label: "GBP/CHF" },
        { flag1: "gb", flag2: "au", label: "GBP/AUD" },
        { flag1: "gb", flag2: "jp", label: "GBP/JPY" }
      ]
    }
  },
  times: [
    { time: "5s", emoji: "⚡", sub: "Ultra" },
    { time: "15s", emoji: "🔥", sub: "Fast" },
    { time: "30s", emoji: "🎯", sub: "Stable" },
    { time: "1m", emoji: "⭐", sub: "Beginner" },
    { time: "3m", emoji: "📊", sub: "Analysis" },
    { time: "5m", emoji: "⏳", sub: "Long" }
  ],
  loadingSteps: ["Connecting to TradingView...", "Fetching indicators...", "Analyzing..."],
  buyIndicators: ["RSI", "MACD", "Volume", "MA Cross", "Bollinger Bands", "Breakout", "Support"],
  sellIndicators: ["RSI", "MACD", "Volume", "MA Cross", "Bollinger Bands", "Resistance", "Breakdown"]
};